version: '3.8'

services:
  smartsearch-db:
    image: postgres:15.3-bullseye
    env_file:
      - ./database/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appNetwork

  smartsearch-app:
    build:
      context: ./backend/smartSearch 
      dockerfile: src/main/docker/Dockerfile.jvm
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - smartsearch-db
    networks:
      - appNetwork

volumes:
  db-data:

networks:
  appNetwork:
    driver: bridge

